# Generated by Django 5.0.14 on 2025-11-26 06:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Driver', 'Driver'), ('Helper', 'Helper'), ('Encoder', 'Encoder')], max_length=10)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Trip', 'On Trip')], default='Available', max_length=15)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('is_hub', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('vin', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tonner_capacity', models.SmallIntegerField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('Maintenance', 'Maintenance')], default='Available', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_code', models.CharField(max_length=50, unique=True)),
                ('scheduled_start_time', models.DateTimeField()),
                ('scheduled_end_time', models.DateTimeField(blank=True, null=True)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_completion_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Transit', 'In Transit'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rescue', 'Rescue'), ('Backload', 'Backload'), ('Ongoing', 'Ongoing'), ('Upcoming', 'Upcoming'), ('Delayed', 'Delayed')], default='Scheduled', max_length=20)),
                ('load_type', models.CharField(blank=True, choices=[('Dry', 'Dry'), ('Chilled', 'Chilled'), ('Ref', 'Ref'), ('Combi', 'Combi')], max_length=10, null=True)),
                ('loading_ref_no', models.CharField(blank=True, max_length=50, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cargo_type', models.CharField(default='General', help_text='e.g., Electronics, Pallets, Loose Cargo', max_length=100)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=10)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trips', to='fleet.customer')),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='destination_trips', to='fleet.location')),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'Driver'}, on_delete=django.db.models.deletion.RESTRICT, related_name='driven_trips', to='fleet.employee')),
                ('helper1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_trips_h1', to='fleet.employee')),
                ('helper2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_trips_h2', to='fleet.employee')),
                ('origin_location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='origin_trips', to='fleet.location')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trips', to='fleet.truck')),
            ],
        ),
        migrations.CreateModel(
            name='TripEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('Loading_Start', 'Loading Start'), ('Loading_Arrival', 'Loading Arrival'), ('Unloading_Start', 'Unloading Start'), ('Unloading_Arrival', 'Unloading Arrival'), ('Trip_Start', 'Trip Start'), ('Trip_End', 'Trip End'), ('Fuel', 'Fuel Transaction'), ('Stopover', 'Planned Stop'), ('Rescue', 'Rescue Event'), ('Delayed', 'Delay Noted')], max_length=20)),
                ('event_timestamp', models.DateTimeField(auto_now_add=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('location_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('document_no', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('encoder', models.ForeignKey(blank=True, limit_choices_to={'role': 'Encoder'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encoded_events', to='fleet.employee')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='fleet.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripFuelLog',
            fields=[
                ('fuel_id', models.AutoField(primary_key=True, serialize=False)),
                ('fuel_ref_no', models.CharField(max_length=50)),
                ('liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('encoder', models.ForeignKey(blank=True, limit_choices_to={'role': 'Encoder'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encoded_fuel_logs', to='fleet.employee')),
                ('fueling_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fuel_logs', to='fleet.location')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='fleet.trip')),
            ],
        ),
    ]
