# Generated by Django 5.0.14 on 2025-11-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='weekly_hours_current',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current hours worked this week for payroll/management tracking.', max_digits=5),
        ),
    ]
