from rest_framework.routers import DefaultRouter
from django.urls import path, include
from . import views

# Create a router instance
router = DefaultRouter()

# 1. Register Master Data ViewSets
# Assuming you have EmployeeViewSet, CustomerViewSet, etc., defined in fleet/views.py
router.register(r'employees', views.EmployeeViewSet)
router.register(r'customers', views.CustomerViewSet)
router.register(r'locations', views.LocationViewSet)
router.register(r'trucks', views.TruckViewSet)

# 2. Register Trip & Transaction ViewSets
router.register(r'trips', views.TripViewSet)
router.register(r'events', views.TripEventViewSet)
router.register(r'fuel_logs', views.TripFuelLogViewSet)

# The urlpatterns now include all routes generated by the router.
# These will be accessible under the prefix defined in your main urls.py (e.g., '/api/').
urlpatterns = [
    # This path includes all the routes registered above:
    # e.g., /api/employees/, /api/trips/1/, /api/locations/
    path('', include(router.urls)),
]